<?php

declare(strict_types=1);

/**
 * Mascot artwork validator.
 *
 * The mascot PNGs are generated by hand and pasted in, so the failure mode is
 * always the same: a file that looks right in the generator's previewer but
 * carries an opaque or painted background, and then shows up on the site as a
 * pale rectangle on the dark sign-in card and the dark sidebar.
 *
 * This tool answers three questions per file:
 *   1. Does it have a real alpha channel?        (read from the PNG header)
 *   2. Is anything actually transparent in it?    (sampled pixels, needs GD)
 *   3. Is the background a painted checkerboard? (sampled edge pixels)
 *
 * Plus the two contract questions: is every documented pose present, and is
 * every file present actually a documented one?
 *
 * Usage:
 *   php tools/mascot_assets.php            report only
 *   php tools/mascot_assets.php --strict   also exit 1 when a PNG is opaque
 *
 * The alpha check reads the PNG chunk headers directly, so it works without the
 * GD extension; only the pixel sampling is skipped when GD is missing.
 */

const MASCOT_DIR = __DIR__ . '/../public/assets/mascot';

/** The 20 character poses the app references (mirrors MascotTest). */
const MASCOT_POSES = [
    'hero', 'point-right', 'point-up', 'point-down', 'thumbs-up', 'celebrate',
    'thinking', 'worried', 'sleeping', 'reading', 'laptop', 'tap-card',
    'chart', 'search', 'star', 'bust',
    'megaphone', 'envelope', 'medal', 'footer-peek',
];

/** The 16 flat stickers, saved with a sticker- prefix. */
const MASCOT_STICKERS = [
    'new', 'tip', 'done', 'star', 'grade-a', 'locked', 'alert', 'wow',
    'saved', 'upload', 'question', 'error', 'pending', 'settings',
    'audit', 'backup',
];

/**
 * Icon-scale marks, saved with a logo- prefix.
 *
 * A separate class from the poses: flat vector, not a lit 3D render, because a
 * shaded head turns to mush at 24px in a browser tab. The mono variant is for
 * print, PDF and anywhere the colour cannot be guaranteed.
 */
const MASCOT_LOGOS = [
    'mark', 'mark-mono',
];

/**
 * Ultrawide compositions, saved with a poster- prefix.
 *
 * The character is confined to one third and the rest is deliberately empty
 * transparent space. That space is reserved for live HTML text - baking the
 * headline into the artwork would make it untranslatable, inaccessible and
 * unresizable.
 */
const MASCOT_POSTERS = [
    'enroll', 'about', 'announce', 'support',
    'portal-login', 'portal-grades', 'portal-schedules', 'portal-updates',
];

/** Wide shallow band used as a section separator. */
const MASCOT_BANDS = [
    'band',
];

/**
 * Tiling textures, saved with a pattern- prefix.
 *
 * MUST tile seamlessly: every motif sits fully inside the canvas with a margin
 * so nothing is sliced at the repeat. Never cropped to their alpha bounds -
 * tools/mascot_optimize.php knows this by the prefix, because trimming a tile
 * leaves a motif with a hard edge that repeats as a visible box.
 */
const MASCOT_PATTERNS = [
    'doodle',
];

/** File-name prefix for each class, keyed the same way as the lists above. */
const MASCOT_CLASS_PREFIXES = [
    'pose'    => '',
    'sticker' => 'sticker-',
    'logo'    => 'logo-',
    'poster'  => 'poster-',
    'band'    => 'divider-',
    'pattern' => 'pattern-',
];

/** The documented lists, in the order they are reported. */
const MASCOT_CLASSES = [
    'pose'    => MASCOT_POSES,
    'sticker' => MASCOT_STICKERS,
    'logo'    => MASCOT_LOGOS,
    'poster'  => MASCOT_POSTERS,
    'band'    => MASCOT_BANDS,
    'pattern' => MASCOT_PATTERNS,
];

/**
 * Every file name the app expects to find, keyed for lookup.
 *
 * @return array<string, string> file name => kind ('pose', 'sticker', 'logo',
 *                                             'poster', 'band' or 'pattern')
 */
function mascot_contract(): array
{
    $contract = [];

    foreach (MASCOT_CLASSES as $kind => $names) {
        $prefix = MASCOT_CLASS_PREFIXES[$kind];

        foreach ($names as $name) {
            $contract[$prefix . $name . '.png'] = $kind;
        }
    }

    return $contract;
}

/**
 * Read width, height, colour type and alpha straight out of the PNG chunks.
 *
 * getimagesize() would be easier, but it does not distinguish "has an alpha
 * channel" from "is actually transparent", and that distinction is the entire
 * point of this tool.
 *
 * @return array{width:int,height:int,colorType:int,alpha:bool,trns:bool,error:string}|null
 */
function mascot_png_info(string $path): ?array
{
    $handle = @fopen($path, 'rb');
    if ($handle === false) {
        return null;
    }

    $info = [
        'width' => 0, 'height' => 0, 'colorType' => -1,
        'alpha' => false, 'trns' => false, 'error' => '',
    ];

    if ((string) fread($handle, 8) !== "\x89PNG\r\n\x1a\n") {
        fclose($handle);
        $info['error'] = 'not a PNG';

        return $info;
    }

    // IHDR is a 4-byte length, a 4-byte type, then exactly 13 bytes of data.
    if ((string) fread($handle, 8) !== "\x00\x00\x00\x0DIHDR") {
        fclose($handle);
        $info['error'] = 'missing IHDR';

        return $info;
    }

    $parts = unpack('Nwidth/Nheight/C1depth/C1color/C1compression/C1filter/C1interlace', (string) fread($handle, 13));

    if ($parts === false) {
        fclose($handle);
        $info['error'] = 'unreadable header';

        return $info;
    }

    $info['width']     = (int) $parts['width'];
    $info['height']    = (int) $parts['height'];
    $info['colorType'] = (int) $parts['color'];

    // Colour type 4 is greyscale+alpha, 6 is truecolour+alpha. Indexed images
    // (3) can still carry transparency, but only through a tRNS chunk.
    $info['alpha'] = in_array($info['colorType'], [4, 6], true);

    // Walk the remaining chunks looking for tRNS.
    while (! feof($handle)) {
        $lengthBytes = fread($handle, 4);
        if ($lengthBytes === false || strlen($lengthBytes) < 4) {
            break;
        }

        $length = unpack('N', $lengthBytes)[1] ?? 0;
        $type   = (string) fread($handle, 4);

        if ($type === 'tRNS') {
            $info['trns']  = true;
            $info['alpha'] = true;
        }

        if ($type === 'IEND') {
            break;
        }

        fseek($handle, $length + 4, SEEK_CUR); // skip payload + CRC
    }

    fclose($handle);

    return $info;
}


/**
 * Sample a coarse grid of pixels to find out whether the image is genuinely
 * see-through, and whether its edges look like a painted checkerboard.
 *
 * @return array{transparent:int,sampled:int,lightEdges:int}|null
 */
function mascot_sample_pixels(string $path): ?array
{
    if (! function_exists('imagecreatefrompng')) {
        return null;
    }

    $image = @imagecreatefrompng($path);
    if ($image === false) {
        return null;
    }

    $width  = imagesx($image);
    $height = imagesy($image);
    $steps  = 24;

    $transparent = 0;
    $sampled     = 0;

    for ($y = 0; $y < $steps; $y++) {
        for ($x = 0; $x < $steps; $x++) {
            $px = (int) (($x + 0.5) / $steps * ($width - 1));
            $py = (int) (($y + 0.5) / $steps * ($height - 1));
            $rgba  = imagecolorat($image, $px, $py);
            $alpha = ($rgba >> 24) & 0x7F;

            $sampled++;

            if ($alpha === 127) {
                $transparent++;
            }
        }
    }

    // Is the border itself a painted background?
    //
    // This walks the true outer pixel border rather than the outer ring of the
    // 24x24 sampling grid. The grid ring is NOT the image edge - it sits about
    // 2% in, roughly 10px on a 509px file - so it samples the artwork itself
    // rather than its background. That is why every sticker read "ok" before
    // tools/mascot_optimize.php trimmed away the transparent margin: the ring
    // landed in that empty margin. Once trimmed, it landed on the stickers' own
    // white outline, which the sticker style spec explicitly allows (#ffffff),
    // and three of them were reported as having a painted checkerboard.
    //
    // A genuine painted background covers the whole border. A highlight or an
    // outline covers a small part of it, so the test is a proportion of the
    // border rather than a raw pixel count - and the count is normalised because
    // a 640x409 sticker has a very different border length from a 548x640 one.
    $borderTotal = 0;
    $borderLight = 0;

    for ($x = 0; $x < $width; $x++) {
        foreach ([0, $height - 1] as $py) {
            $rgba  = imagecolorat($image, $x, $py);
            $alpha = ($rgba >> 24) & 0x7F;
            $borderTotal++;

            // 0 is fully opaque, 127 fully transparent. Require a substantially
            // solid pixel: a semi-transparent fringe cannot produce a visible box.
            if ($alpha > 31) {
                continue;
            }

            $r = ($rgba >> 16) & 0xFF;
            $g = ($rgba >> 8) & 0xFF;
            $b = $rgba & 0xFF;

            if ($r >= 235 && $g >= 235 && $b >= 235) {
                $borderLight++;
            }
        }
    }

    for ($y = 0; $y < $height; $y++) {
        foreach ([0, $width - 1] as $px) {
            $rgba  = imagecolorat($image, $px, $y);
            $alpha = ($rgba >> 24) & 0x7F;
            $borderTotal++;

            if ($alpha > 31) {
                continue;
            }

            $r = ($rgba >> 16) & 0xFF;
            $g = ($rgba >> 8) & 0xFF;
            $b = $rgba & 0xFF;

            if ($r >= 235 && $g >= 235 && $b >= 235) {
                $borderLight++;
            }
        }
    }

    imagedestroy($image);

    // Reported as a percentage so the verdict means the same thing for every
    // aspect ratio. 50% of a solid-light border is a background; 50% of a
    // highlight running along a badge is not.
    $lightEdges = $borderTotal > 0 ? (int) round($borderLight / $borderTotal * 100) : 0;

    return ['transparent' => $transparent, 'sampled' => $sampled, 'lightEdges' => $lightEdges];
}

$strict = in_array('--strict', $argv, true);
$dir    = realpath(MASCOT_DIR);

if ($dir === false || ! is_dir($dir)) {
    fwrite(STDERR, "mascot folder not found\n");
    exit(2);
}

$files    = glob($dir . '/*.png') ?: [];
$contract = mascot_contract();

sort($files);

$opaque  = [];
$missing = [];
$extra   = [];

echo 'Tappy artwork - ' . basename($dir) . "\n";
echo str_repeat('-', 96) . "\n";
printf("%-44s %-11s %-6s %s\n", 'file', 'size', 'alpha', 'verdict');

foreach ($files as $file) {
    $name = basename($file);
    $info = mascot_png_info($file);

    if ($info === null || $info['error'] !== '') {
        printf("%-44s %-11s %-6s %s\n", $name, '-', 'no', $info === null ? 'unreadable' : $info['error']);
        $opaque[] = $name;
        continue;
    }

    $verdict = 'ok';
    $sample  = mascot_sample_pixels($file);

    if (! $info['alpha']) {
        $verdict  = 'OPAQUE - no alpha channel, the background will show';
        $opaque[] = $name;
    } elseif ($sample !== null && $sample['transparent'] === 0) {
        // An alpha channel that is opaque everywhere is just an opaque file
        // saved as RGBA: it passes a naive "has alpha" check and still shows
        // a box on the page.
        $verdict  = 'alpha present but nothing is transparent';
        $opaque[] = $name;
    } elseif ($sample !== null && $sample['lightEdges'] >= 35) {
        // A percentage of the border, not a raw count. 35% rather than 50%
        // because an alternating checkerboard only lights roughly half of the
        // perimeter - a synthetic white checkerboard measured 53%, and one
        // starting on a dark square would land near 47% and slip past a 50% cut.
        // A badge highlight or outline is a minority of the border, so 35%
        // still clears those comfortably.
        $verdict = sprintf('suspicious: %d%% of the border is solid light, looks like a painted checkerboard', $sample['lightEdges']);
    }

    // Weight is not a correctness problem, so it is reported but never counted as
    // a failure. The generator writes 1.7-2.3 MB files and every page that shows
    // Tappy pays for the poses it uses; tools/mascot_optimize.php is the fix.
    //
    // The threshold is 500 KB to match DEFAULT_MAX_WEIGHT in the optimiser. It
    // was previously 450 KB, which flagged bust.png (461 KB) and advised running
    // the optimiser - advice that turns out to be worth a 1% saving, because
    // that file is legitimately heavy rather than bloated. A warning people
    // learn to ignore is worse than no warning.
    $bytes  = (int) @filesize($file);
    $weight = $bytes > 500 * 1024
        ? sprintf(' | heavy: %s, run tools/mascot_optimize.php', mascot_format_bytes($bytes))
        : '';

    printf(
        "%-44s %-11s %-6s %s%s\n",
        $name,
        $info['width'] . 'x' . $info['height'],
        $info['alpha'] ? 'yes' : 'NO',
        $verdict,
        $weight
    );
}

/** Human-readable file size for the weight warning. */
function mascot_format_bytes(int $bytes): string
{
    return $bytes >= 1048576
        ? round($bytes / 1048576, 2) . ' MB'
        : round($bytes / 1024) . ' KB';
}

foreach ($contract as $file => $kind) {
    if (! is_file($dir . '/' . $file)) {
        $missing[$kind][] = $file;
    }
}

foreach ($files as $file) {
    $name = basename($file);
    if (! isset($contract[$name])) {
        $extra[] = $name;
    }
}

echo str_repeat('-', 96) . "\n";

foreach (MASCOT_CLASSES as $kind => $names) {
    printf("%-9s %d/%d present\n", $kind . ':', count($names) - count($missing[$kind] ?? []), count($names));
}

foreach (MASCOT_CLASSES as $kind => $names) {
    if (($missing[$kind] ?? []) === []) {
        continue;
    }

    echo "\nMISSING " . strtoupper($kind) . " (referenced by the app, not generated yet):\n";
    foreach ($missing[$kind] as $file) {
        echo '  - ' . $file . "\n";
    }
}

if ($opaque !== []) {
    echo "\nNOT TRANSPARENT (these show a visible box on the dark UI):\n";
    foreach ($opaque as $file) {
        echo '  - ' . $file . "\n";
    }
}

if ($extra !== []) {
    echo "\nUNDOCUMENTED (on disk, but no view or prompt refers to them):\n";
    foreach ($extra as $file) {
        echo '  - ' . $file . "\n";
    }
}

if (! is_file($dir . '/PROMPTS.md')) {
    echo "\nPROMPTS.md is missing — the artwork contract is undocumented.\n";
}

if (! function_exists('imagecreatefrompng')) {
    echo "\nnote: the GD extension is not loaded, so pixel sampling was skipped\n";
    echo "      (the alpha-channel checks above are still accurate).\n";
}

// A missing documented pose is fatal on every run. An opaque file is only
// fatal under --strict, because the artwork is still being generated by hand
// and the site degrades cleanly without it.
if ($missing !== []) {
    exit(1);
}

if ($strict && $opaque !== []) {
    exit(1);
}

exit(0);
