<?php

use CodeIgniter\Test\CIUnitTestCase;

/**
 * The artwork contract, enforced in CI.
 *
 * Every other mascot test is about code. This one is about the PNGs, and it is
 * opt-in on purpose: the artwork is generated by hand and is still incomplete,
 * so a permanently failing assertion would just train everyone to ignore it.
 *
 * Enable it with MASCOT_STRICT_ASSETS=1, ideally once the full set of genuinely
 * transparent files has been pasted in. Until then:
 *
 *   php vendor/bin/phpunit --filter MascotAssets      # skipped
 *   MASCOT_STRICT_ASSETS=1 php vendor/bin/phpunit --filter MascotAssets
 *
 * @internal
 */
final class MascotAssetsTest extends CIUnitTestCase
{
    private function dir(): string
    {
        return ROOTPATH . 'public/assets/mascot';
    }

    private function strict(): bool
    {
        $flag = getenv('MASCOT_STRICT_ASSETS');

        return $flag !== false && $flag !== '' && $flag !== '0';
    }

    /**
     * Read the PNG header directly. getimagesize() reports the channel count
     * but not whether the file carries an alpha channel, and "has alpha" vs
     * "is actually see-through" is the distinction that matters here.
     */
    private function hasAlphaChannel(string $file): ?bool
    {
        $handle = @fopen($file, 'rb');
        if ($handle === false) {
            return null;
        }

        if ((string) fread($handle, 8) !== "\x89PNG\r\n\x1a\n") {
            fclose($handle);

            return null;
        }

        if ((string) fread($handle, 8) !== "\x00\x00\x00\x0DIHDR") {
            fclose($handle);

            return null;
        }

        $parts = unpack('Nwidth/Nheight/C1depth/C1color', (string) fread($handle, 10));
        fclose($handle);

        if ($parts === false) {
            return null;
        }

        $colorType = (int) $parts['color'];

        // 4 = greyscale + alpha, 6 = truecolour + alpha. Indexed images can
        // carry transparency only through a tRNS chunk, which is not scanned
        // for here, so they are reported as not-alpha to stay strict.
        return in_array($colorType, [4, 6], true);
    }

    public function testEveryPastedPngHasAnAlphaChannel(): void
    {
        if (! $this->strict()) {
            $this->markTestSkipped('Set MASCOT_STRICT_ASSETS=1 to enforce the artwork contract.');
        }

        $files = glob($this->dir() . '/*.png') ?: [];
        $this->assertNotEmpty($files, 'no artwork found to check');

        $opaque = [];

        foreach ($files as $file) {
            if ($this->hasAlphaChannel($file) !== true) {
                $opaque[] = basename($file);
            }
        }

        $this->assertSame(
            [],
            $opaque,
            'these files have no alpha channel, so their background shows as a pale box on the dark UI: ' . implode(', ', $opaque)
        );
    }
}
